import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Outlet, Link, createRootRouteWithContext, useRouter, HeadContent, Scripts, type ErrorComponentProps } from "@tanstack/react-router";
import { useEffect, type ReactNode } from "react";
import appCss from "../styles.css?url";
import { reportLovableError } from "../lib/lovable-error-reporting";
import { PageShell } from "@/components/fazero/SiteShell";
import { Button } from "@/components/ui/button";
function NotFoundComponent(){return <PageShell><div className="relative grid min-h-[75vh] place-items-center overflow-hidden bg-secondary px-5 pt-24 text-center"><svg className="absolute inset-0 h-full w-full opacity-30" viewBox="0 0 100 50"><path d="M0 25 L35 25 L48 10 M35 25 L62 38 L100 38" fill="none" stroke="currentColor" strokeWidth=".15" className="flow-line"/></svg><div className="relative"><p className="label">Error 404</p><h1 className="mt-6 font-display text-6xl sm:text-8xl">Looks Like This Page<br/>Took a Wrong Turn.</h1><div className="mt-10 flex flex-wrap justify-center gap-3"><Button asChild className="h-12 rounded-none"><Link to="/">Back Home</Link></Button><Button asChild variant="outline" className="h-12 rounded-none"><Link to="/services">Explore Services</Link></Button><Button asChild variant="outline" className="h-12 rounded-none"><Link to="/contact">Contact Us</Link></Button></div></div></div></PageShell>}
function ErrorComponent({error,reset}:ErrorComponentProps){console.error(error);const router=useRouter();useEffect(()=>reportLovableError(error,{boundary:"tanstack_root_error_component"}),[error]);return <div className="grid min-h-screen place-items-center bg-background px-5 text-center"><div><h1 className="font-display text-5xl">This page didn’t load.</h1><p className="mt-4 text-muted-foreground">Please try again or return home.</p><div className="mt-7 flex justify-center gap-3"><Button onClick={()=>{router.invalidate();reset()}}>Try again</Button><Button asChild variant="outline"><a href="/">Go home</a></Button></div></div></div>}
export const Route=createRootRouteWithContext<{queryClient:QueryClient}>()({head:()=>({meta:[{charSet:"utf-8"},{name:"viewport",content:"width=device-width, initial-scale=1"},{property:"og:type",content:"website"},{property:"og:site_name",content:"Fazero International"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"stylesheet",href:appCss},{rel:"preconnect",href:"https://fonts.googleapis.com"},{rel:"preconnect",href:"https://fonts.gstatic.com",crossOrigin:"anonymous"},{rel:"stylesheet",href:"https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@500;600&family=Manrope:wght@400;500;600;700&display=swap"},{rel:"icon",href:"/favicon.ico",type:"image/x-icon"}],scripts:[{type:"application/ld+json",children:JSON.stringify({"@context":"https://schema.org","@type":"Organization",name:"Fazero International",email:"sales@fazerointernational.com",telephone:["+91 95857 17122","+91 87543 63952","+1 (607) 297-0320"],description:"Business growth consultancy combining strategy, marketing, technology, AI and sales."})}]}),shellComponent:RootShell,component:RootComponent,notFoundComponent:NotFoundComponent,errorComponent:ErrorComponent});
function RootShell({children}:{children:ReactNode}){return <html lang="en"><head><HeadContent/></head><body>{children}<Scripts/></body></html>}
function RootComponent(){const {queryClient}=Route.useRouteContext();return <QueryClientProvider client={queryClient}><PageShell><Outlet/></PageShell></QueryClientProvider>}
