import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowDownRight, ArrowRight, Globe2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { LineNetwork } from "@/components/fazero/LineNetwork";
import { CTA, Eyebrow, ResultsBand, SectionIntro, ServicesGrid } from "@/components/fazero/Sections";
import { pageHead } from "@/lib/seo";
import { resources } from "@/lib/fazero-data";
const description="Fazero International helps businesses grow through digital marketing, SEO, AEO, GEO, AI implementation, technology solutions, referral marketing, business strategy and sales consulting across India, Dubai, UAE, Malaysia and the USA.";
export const Route=createFileRoute("/")({head:()=>({...pageHead("Fazero International | Business Growth Consultancy, Digital Marketing & AI",description,"/"),scripts:[{type:"application/ld+json",children:JSON.stringify({"@context":"https://schema.org","@type":"ProfessionalService",name:"Fazero International",description,areaServed:["India","United Arab Emirates","Malaysia","United States"]})}]}),component:Index});
function Index(){return <>
<section className="relative min-h-[92vh] overflow-hidden bg-secondary pt-20"><LineNetwork/><div className="relative mx-auto grid min-h-[calc(92vh-5rem)] max-w-[1440px] content-center px-5 py-20 lg:px-10"><div className="reveal-up max-w-5xl"><Eyebrow>Business Growth Consultancy</Eyebrow><h1 className="font-display text-6xl leading-[.9] sm:text-7xl lg:text-[7.5rem]">Turn Your Business Potential Into <em className="font-normal text-primary">Measurable Growth.</em></h1><p className="mt-8 max-w-2xl text-base leading-8 text-foreground/65">Fazero International helps businesses build stronger brands, acquire customers, adopt emerging technologies, implement AI, improve sales and create scalable growth strategies across global markets.</p><div className="mt-9 flex flex-wrap gap-3"><Button asChild className="h-14 rounded-none px-6"><Link to="/contact">Book a Consultation <ArrowRight/></Link></Button><Button asChild variant="outline" className="h-14 rounded-none bg-background/30 px-6"><Link to="/services">Explore Our Services <ArrowDownRight/></Link></Button></div></div><div className="absolute bottom-7 right-5 hidden border border-foreground/15 bg-background/45 p-5 backdrop-blur md:block lg:right-10"><p className="label mb-4">Portfolio snapshot</p><div className="flex gap-8"><Data value="2,449+" label="Leads"/><Data value="236" label="Conversions"/><Data value="5" label="Programs"/></div></div></div></section>
<section className="py-24"><div className="mx-auto max-w-[1440px] px-5 lg:px-10"><SectionIntro eyebrow="Integrated capability" title="Everything You Need to Build and Scale." body="Growth is not a single channel. We connect strategy, acquisition, technology and sales so each part of the business strengthens the next."/><ServicesGrid limit={6}/><div className="mt-8 text-right"><Button asChild variant="link"><Link to="/services">View every capability <ArrowRight/></Link></Button></div></div></section>
<ResultsBand/>
<section className="py-24"><div className="mx-auto max-w-[1440px] px-5 lg:px-10"><SectionIntro eyebrow="The growth framework" title="From Strategy to Scale." body="A connected operating path designed to turn insight into repeatable growth."/><div className="relative mt-16 grid gap-px bg-border lg:grid-cols-5">{[["01","Discover","Understand the business."],["02","Strategize","Build the roadmap."],["03","Build","Implement the solution."],["04","Accelerate","Optimize acquisition and conversion."],["05","Scale","Create repeatable systems."]].map(([n,t,d])=><div key={n} className="relative min-h-56 bg-background p-7"><span className="text-xs text-primary">{n}</span><h3 className="mt-14 font-display text-3xl">{t}</h3><p className="mt-3 text-sm text-muted-foreground">{d}</p><span className="absolute -right-1 top-1/2 z-10 size-2 bg-primary"/></div>)}</div></div></section>
<section className="bg-secondary py-24"><div className="mx-auto max-w-[1440px] px-5 lg:px-10"><SectionIntro eyebrow="Search is changing" title="Be Found. Be the Answer. Be Understood."/><div className="mt-14 grid gap-5 lg:grid-cols-3">{[["SEO","Be Found.","Build visibility through technical strength, useful content and search intent."],["AEO","Be the Answer.","Structure clear answers for question-led discovery and answer engines."],["GEO","Be Understood by AI.","Clarify entities, expertise and context for generative search systems."]].map(([k,t,d])=><article key={k} className="relative overflow-hidden border border-border bg-background p-8"><div className="absolute -right-16 -top-16 size-48 rounded-full border border-primary/30"/><p className="label">{k}</p><h3 className="mt-12 font-display text-4xl">{t}</h3><p className="mt-4 text-sm leading-7 text-muted-foreground">{d}</p></article>)}</div></div></section>
<section className="overflow-hidden py-24"><div className="mx-auto grid max-w-[1440px] gap-14 px-5 lg:grid-cols-2 lg:items-center lg:px-10"><SectionIntro eyebrow="Our presence" title="Think Local. Build Global." body="Fazero works across market contexts in India, the UAE, Malaysia and the USA. These are markets we serve—not claims of physical offices."/><div className="relative aspect-[16/10] border border-border bg-secondary"><Globe2 className="absolute left-1/2 top-1/2 size-52 -translate-x-1/2 -translate-y-1/2 stroke-[.4] text-primary"/><svg className="absolute inset-0 size-full" viewBox="0 0 100 60"><path d="M18 37 C37 15 52 47 67 29 S83 20 91 31" fill="none" stroke="currentColor" strokeWidth=".35" className="flow-line text-primary"/>{[[18,37],[67,29],[80,22],[91,31]].map(([x,y],i)=><circle key={i} cx={x} cy={y} r="1" className="fill-primary"/>)}</svg><div className="absolute inset-x-5 bottom-5 grid grid-cols-4 text-center text-[10px] uppercase tracking-[.1em]"><span>India</span><span>Dubai</span><span>Malaysia</span><span>USA</span></div></div></div></section>
<section className="py-24"><div className="mx-auto max-w-[1440px] px-5 lg:px-10"><div className="flex flex-col justify-between gap-8 sm:flex-row sm:items-end"><SectionIntro eyebrow="Growth intelligence" title="Ideas for the next market."/><Button asChild variant="outline" className="rounded-none"><Link to="/resources">Explore all resources <ArrowRight/></Link></Button></div><div className="mt-14 grid border-l border-t border-border lg:grid-cols-3">{resources.slice(0,3).map(r=><Link key={r.slug} to="/resources/$slug" params={{slug:r.slug}} className="group border-b border-r border-border p-7"><p className="label">{r.category}</p><h3 className="mt-10 font-display text-3xl group-hover:text-primary">{r.title}</h3><p className="mt-4 text-sm leading-7 text-muted-foreground">{r.excerpt}</p><ArrowRight className="mt-8 size-4 text-primary"/></Link>)}</div></div></section><CTA/></>}
function Data({value,label}:{value:string;label:string}){return <div><strong className="font-display text-2xl">{value}</strong><span className="mt-1 block text-[9px] uppercase text-muted-foreground">{label}</span></div>}
