import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { CTA, Eyebrow } from "@/components/fazero/Sections";
import { resources } from "@/lib/fazero-data";
const articles:Record<string,{intro:string;steps:string[];answer:string}>={
"how-to-get-clients-in-dubai":{intro:"A focused Dubai acquisition plan connects credibility, local discoverability, relationships and responsive sales execution.",answer:"To get clients in Dubai, define a market-specific offer, build local visibility, develop referral and partnership channels, run focused outreach or advertising, and follow every qualified lead through a CRM.",steps:["Position for a specific buyer and need","Build local SEO and LinkedIn visibility","Develop referrals, partnerships and networks","Use focused paid campaigns where appropriate","Track, qualify and follow up consistently"]},
"how-to-get-clients-in-india":{intro:"India rewards focus. Choose the audience, geography and buying problem before selecting channels.",answer:"Businesses get clients in India by combining clear positioning with locally relevant content, search visibility, referral relationships, targeted campaigns and a disciplined sales process.",steps:["Select a focused segment","Clarify the offer","Build relevant visibility","Generate and qualify demand","Improve follow-up"]},
"indian-company-get-dubai-clients":{intro:"India-to-Dubai growth should progress from evidence to positioning, then acquisition and sales.",answer:"An Indian company can get Dubai clients by researching a defined segment, adapting its positioning, establishing a credible digital presence, creating local relationships, generating leads and using structured follow-up.",steps:["Market Research","Positioning","Digital Presence","Lead Generation","Sales","CRM & Follow-Up","Customer Acquisition"]},
"how-to-generate-b2b-leads":{intro:"B2B lead generation is a connected system rather than a list of isolated campaigns.",answer:"Generate B2B leads by defining an ideal buyer, publishing useful expertise, combining inbound and outbound channels, creating a clear offer and following up with context.",steps:["Define the ideal account","Map buying problems","Create useful proof and content","Activate search, outreach and referrals","Qualify and nurture"]},
"seo-vs-aeo-vs-geo":{intro:"Three disciplines help a business remain discoverable as search behavior changes.",answer:"SEO helps pages rank in search results, AEO structures content as direct answers, and GEO helps generative AI systems understand and reference a business or its expertise.",steps:["SEO: earn search visibility","AEO: answer clear questions","GEO: clarify entities and context","Connect all three through useful content"]},
"ai-customer-acquisition":{intro:"AI can increase speed and consistency when it supports—not replaces—sound acquisition strategy.",answer:"AI can improve customer acquisition through faster research, content support, lead qualification, personalized follow-up, customer support and workflow automation.",steps:["Research audiences","Support content production","Qualify incoming leads","Personalize communication","Automate routine handoffs"]},
"build-referral-marketing-system":{intro:"Referrals become dependable when trust is supported by a repeatable process.",answer:"Build a referral system by defining who should refer, what an ideal introduction looks like, when to ask, how to make introductions easy and how to track outcomes.",steps:["Identify advocates","Define the ideal referral","Create a clear request","Make introductions easy","Track and nurture relationships"]},
"expand-indian-business-into-dubai":{intro:"Expansion is a sequence of validated decisions, not a single campaign.",answer:"Expand into Dubai by validating demand, adapting positioning, establishing digital credibility, building local relationships, testing acquisition channels and creating a reliable sales process.",steps:["Validate the market","Adapt positioning","Build credibility","Create local pathways","Test lead generation","Operationalize sales"]}}
export const Route=createFileRoute("/resources/$slug")({loader:({params})=>{const meta=resources.find(r=>r.slug===params.slug),article=articles[params.slug];if(!meta||!article)throw notFound();return {meta,article}},head:({params,loaderData})=>({meta:[{title:`${loaderData?.meta.title??"Resource"} | Fazero International`},{name:"description",content:loaderData?.meta.excerpt},{property:"og:title",content:loaderData?.meta.title},{property:"og:description",content:loaderData?.meta.excerpt},{property:"og:type",content:"article"},{property:"og:url",content:`/resources/${params.slug}`},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:`/resources/${params.slug}`}],scripts:[{type:"application/ld+json",children:JSON.stringify({"@context":"https://schema.org","@type":"Article",headline:loaderData?.meta.title,description:loaderData?.meta.excerpt,publisher:{"@type":"Organization",name:"Fazero International"}})}]}),component:Article});
function Article(){const {meta,article}=Route.useLoaderData();return <><article><header className="bg-secondary pb-20 pt-40"><div className="mx-auto max-w-4xl px-5"><nav className="mb-9 text-xs text-muted-foreground"><Link to="/resources">Resources</Link> / {meta.category}</nav><Eyebrow>{meta.category}</Eyebrow><h1 className="font-display text-5xl leading-[.98] sm:text-7xl">{meta.title}</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-muted-foreground">{article.intro}</p></div></header><div className="mx-auto max-w-4xl px-5 py-20"><section className="border-l-2 border-primary pl-7"><h2 className="font-display text-3xl">The short answer</h2><p className="mt-4 text-lg leading-8 text-muted-foreground">{article.answer}</p></section><section className="mt-16"><h2 className="font-display text-4xl">A practical path</h2><ol className="mt-8 border-t border-border">{article.steps.map((s,i)=><li key={s} className="grid grid-cols-[3rem_1fr] border-b border-border py-6"><span className="text-xs text-primary">0{i+1}</span><span className="font-display text-2xl">{s}</span></li>)}</ol></section><p className="mt-12 text-sm leading-7 text-muted-foreground">The right mix depends on your market, offer, audience and current capabilities. Validate the opportunity before scaling investment.</p></div></article><CTA/></>}
