import { Link } from "@tanstack/react-router";
import { Menu, X, ArrowUpRight, Mail, Phone } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Brand } from "./Brand";
const nav = [["Services","/services"],["Case Studies","/case-studies"],["About","/about"],["Resources","/resources"],["Presence","/presence"],["Contact","/contact"]] as const;
export function Header(){ const [open,setOpen]=useState(false); return <header className="fixed inset-x-0 top-0 z-50 border-b border-border/70 bg-background/90 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-[1440px] items-center justify-between px-5 lg:px-10"><Brand/><nav className="hidden items-center gap-7 lg:flex">{nav.map(([label,to])=><Link key={to} to={to} activeProps={{className:"text-primary"}} className="nav-link text-[11px] font-semibold uppercase tracking-[0.12em] text-foreground/70">{label}</Link>)}</nav><div className="flex items-center gap-2"><Button asChild className="hidden h-11 rounded-none px-5 sm:inline-flex"><Link to="/contact">Book a Consultation <ArrowUpRight/></Link></Button><Button size="icon" variant="ghost" className="lg:hidden" onClick={()=>setOpen(!open)} aria-label={open?"Close menu":"Open menu"}>{open?<X/>:<Menu/>}</Button></div></div>{open&&<nav className="border-t border-border bg-background p-5 lg:hidden">{nav.map(([label,to])=><Link key={to} to={to} onClick={()=>setOpen(false)} className="block border-b border-border py-4 font-display text-2xl">{label}</Link>)}<Button asChild className="mt-5 h-12 w-full rounded-none"><Link to="/contact" onClick={()=>setOpen(false)}>Book a Consultation</Link></Button></nav>}</header> }
export function Footer(){return <footer className="bg-[#151515] text-[#F5F0E8]"><div className="gold-rule"/><div className="mx-auto max-w-[1440px] px-5 py-16 lg:px-10"><div className="grid gap-12 border-b border-white/15 pb-14 lg:grid-cols-[1.4fr_1fr_1fr_1fr]"><div><Brand light/><p className="mt-7 max-w-xs font-display text-3xl">Build. Scale. Grow.</p><p className="mt-3 text-sm text-[#F5F0E8]/55">Business Growth Consultancy</p></div><FooterList title="Explore" items={nav}/><FooterList title="Services" items={[["Digital Marketing","/services"],["Technology & AI","/services"],["SEO, AEO & GEO","/services"],["Business Strategy","/services"],["Sales","/services"]]}/><div><p className="label text-[#C9A45C]">Contact</p><a className="mt-5 flex items-center gap-2 text-sm" href="mailto:sales@fazerointernational.com"><Mail className="size-4"/>sales@fazerointernational.com</a><a className="mt-4 flex items-center gap-2 text-sm" href="tel:+919585717122"><Phone className="size-4"/>+91 95857 17122</a><a className="mt-3 block pl-6 text-sm" href="tel:+918754363952">+91 87543 63952</a><a className="mt-3 block pl-6 text-sm" href="tel:+16072970320">+1 (607) 297-0320</a></div></div><div className="flex flex-col gap-4 pt-7 text-xs text-[#F5F0E8]/45 sm:flex-row sm:items-center sm:justify-between"><p>© 2026 Fazero International. All Rights Reserved.</p><div className="flex gap-5"><Link to="/privacy-policy">Privacy</Link><Link to="/terms">Terms</Link><Link to="/cookie-policy">Cookies</Link></div></div></div></footer>}
function FooterList({title,items}:{title:string;items:readonly (readonly [string,string])[]}){return <div><p className="label text-[#C9A45C]">{title}</p><div className="mt-4 space-y-3">{items.map(([label,to])=><Link key={label} to={to} className="block text-sm text-[#F5F0E8]/70 hover:text-[#C9A45C]">{label}</Link>)}</div></div>}
export function PageShell({children}:{children:React.ReactNode}){return <><Header/><main>{children}</main><Footer/></>}
